### ISSUE TITLE
پیشنهاد توسعه

### ISSUE THREAD

**Issue by mehrdadashtari** [mehdisadeghi/jekyll-jalali#10]
<div dir="rtl" lang="fa">سلام پیشنهادی دارم برای افزودن قابلیت نمایش رویداد به برنامه ای که توسعه دادید

الان که همه ی سیستم ها به اینترنت متصل هستند پیشنهاد میکنم ارتباط با ای پی آي های تقویم رو هم در این سورس خوب پیاده سازی کنید
خودم از این سرویس زیاد استفاده میکنم </div>
<a href="https://apieco.ir/api/farsicalendar">وب سرویس تقویم فارسی</a>

<div dir="rtl" lang="fa">اطلاعات خوبی ارائه میده مثل وقایع و مناسبت های هر روز و دریافت رویداد در حالت شمسی و قمری و میلادی</div>

**Comment by mehdisadeghi** [comment]
<div dir="ltr">
ممنون بابت پیشنهادت. راه درست استفاده از سرویسی که نوشتی نوشتن یک sdk است. این کار هم معمولا توسط خود برنامه‌نویس‌های هر پروژه انجام می‌شه، لااقل برای زبان‌های مهم. این لایبرری هم یک وظیفه‌ی کوچک داره که داره به درستی انجام می‌ده. من پیشنهاد می‌کنم اگر اون سرویس برات ارزشمنده یک پلاگین جکیل جداگانه بنویسی. در پلاگین جداگانه‌ات می‌تونی از کد این لایبرری هم استفاده کنی.
</div>
