### ISSUE TITLE
کمک برای نصب

### ISSUE THREAD

**Issue by xtoolkit** [mehdisadeghi/jekyll-jalali#2]
سلام
خسته نباشید
میتونید بهم کمک کنید که این ماژول رو برای رپوم ست کنم؟
https://github.com/xtoolkit/blog.arshen.ir
تشکر

**Comment by mehdisadeghi** [comment]
<div style="direction:rtl" dir=rtl>
سلام
کاری نداره. فایل
 jdate
 رو کپی کنید داخل فولدر 
_plugins
به ریپوی من نگاه کنید همه چیز مشخصه. پروسه نصب خاصی وجود نداره.
</div>

**Comment by xtoolkit** [comment]
حقیقتا من تلاشم رو کردم
و چیزی نشون نمیده
از دوستان پرسیدم میگن به خاطر مسائل امنیتی پلاگین کار نمیکنه
شما چی پیشنهاد میکنید؟

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
من ریپوزیتوری شما رو دیدم. ظاهرا که شما دستورالعمل رو دنبال نکردی. نه فولدر _plugins در ریپوزیتوری شما هست و نه gem: jalalidate داخل فایل کانفیگ جکیل اضافه شده. لطفا README همین پروژه رو هم خوب ببینید.
</div>

**Comment by xtoolkit** [comment]
این که میگم تلاشم رو کردم مربوط به دو هفته پیش میشه
خوب بدیهی هست که وقتی کار نکرد کن هم برداشتمش

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
پیشنهاد من اینه که شما تغییرات رو انجام بدین و لوکال با bundler  تست کنید. اول install و بعد 
bunlder exec jekyll serve
رو اجرا کنید.
در ضمن بیلدر وبسایت من هم آنلاینه. می‌تونید ببینید و با مال خودتون مقایسه کنید. من وقتی می‌تونم به شما کمک کنم که مشکل شما معلوم باشه و دقیقا شرح بدین و البته به این برنامه مربوط باشه.
https://app.wercker.com/mehdi/mehdix.ir/runs
</div>
