### ISSUE TITLE
English numbers

### ISSUE THREAD

**Issue by perpi** [mehdisadeghi/jekyll-jalali#3]
I used the code `{{ page.date | jdate: "%A %d %b %Y"}}`, but it generates english numbers like this:

‫شنبه 12 فروردین 1396

While I was expected for:

‫شنبه ۱۲ فروردین ۱۳۹۶

What should I do to turn numbers to Farsi?

**Comment by mehdisadeghi** [comment]
For mapping European style numbers to Arabic style numbers I use [another filter](https://github.com/mehdisadeghi/jekyll-hinduarabic). Perhaps it makes more sense to merge that filter into this repository.

**Comment by perpi** [comment]
Ah, thanks for the hint. Now it works well.

Anyway, 'merging' would be a nice idea.

**Comment by mehdisadeghi** [comment]
I'll consider displaying numbers based on the language set in the context in #4

**Comment by perpi** [comment]
Hi. Has the plugin taken any change? I'm getting this error:

`Liquid Exception: Liquid error (line 16): invalid arguments or invalid Jalali date in /_layouts/post.html`

    Line 16:     <span>{{ page.date | jdate: "%A %d %b %Y" | habify }}</span>

**Comment by mehdisadeghi** [comment]
@perpi which Ruby version are you using? I released a new `jalalidate` gem version which uses `Integer` instead of `Bignum`. That's the only change that I could think of.

**Comment by perpi** [comment]
`$ ruby --version`
`ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]`

jekyll version: `3.6.2`

![screenshot from 2017-11-23 02-51-51](https://user-images.githubusercontent.com/7093244/33153808-5b0c3312-cff9-11e7-96fe-60828ac9c1b4.png)

But the [GitLab](https://gitlab.com) deployment process is failed too, while it probably uses the latest version.

**Comment by perpi** [comment]
Hmmm, no idea?

**Comment by mehdisadeghi** [comment]
@perpi you have to use either ruby 2.4 or use an older version of `jalalidate` such as v0.3.3.

**Comment by mehdisadeghi** [comment]
I also released a new version of `jekyll-jalali` that solves your problem by forcing v0.3.3 of `jalalidate` for the time being.

**Comment by perpi** [comment]
Yoohoo, Now it's working again. Thanks bro.

 ‌ ‌
 ‌ ‌
> you have to use either ruby 2.4 

Yeah, but it's not available in the Ubuntu repo yet. I'm afraid of installing stuff out of official repositories.

**Comment by mehdisadeghi** [comment]
@perpi 

After that release I am getting complains from other users to upgrade `jekyll-jalali` so that they don't get `FixNum is deprecated` warnings. 

However, you can still pinpoint the older `jekyll-jalali` release in your `Gemfile`. It is actually very easy. You need to slightly change your Gemfile:

```
group :jekyll_plugins do
   gem "jekyll-jalali", "= 0.1.1"
   gem "jekyll-hinduarabic"
end
```

If you had any problems, please open a new issue.

**Comment by alihardan** [comment]
<div dir="rtl">
اگر کسی نمی‌خواد برای این کار از یک فیلترِ جدید استفاده کنه، این کارِش رو راه میندازه:
</div>

    {{ post.date | jdate: "%d %b %Y" | replace: "0", "۰" | replace: "1", "۱" | replace: "2", "۲" | replace: "3", "۳" | replace: "4", "۴" | replace: "5", "۵" | replace: "6", "۶" | replace: "7", "۷" | replace: "8", "۸" | replace: "9", "۹" }}
