### ISSUE TITLE
Did not work when deploy on github

### ISSUE THREAD

**Issue by beigirad** [mehdisadeghi/jekyll-jalali#8]
<div dir="rtl" lang="fa">
هر طوری که بود موفق شدم پلاگین رو نصب کنم. و روی لوکال بدرستی نمایش داده میشه.
اما وقتی فایل هارو کامیت میکنم٬ تبدیل تاریخ ها انجام نمیشه!
این هم آدرس 

[بلاگ من ](http://beigirad.github.io/blog)
</div>
<div dir="rtl" lang="fa">
همچنین این مورد رو بگم
من فقط فایل های مربوط به جکیل رو دیپلوی میکنم و از کامیت کردن فایل های خروجی _site خودداری میکنم.

فکر میکنم توی وبلاگ شما هم که بدرستی کار میکنه دلیلش این باشه که شما فایل های html css نهایی رو کامیت میکنید!

امیدوارم تونسته باشم مشکل رو برسونم
</div>

**Comment by mehdisadeghi** [comment]
اول اینکه چون لوکال کار کرده یعنی پلاگین هیچ مشکلی نداره و اشکال در تنظیمات شماست.
جکیل از پلاگینهای دلخواه پشتیبانی نمی‌کنه، باید با یک‌سرویس خارجی بیلد و در گیتهاب پوش کنی. راه حل دیگری نیست.

**Comment by beigirad** [comment]
<div dir="rtl">
بابت پاسخ سریعتون متشکرم

راستش من خیلی از پلاگین و زبان روبی سر درنیاوردم.

میخواستم بدونم امکانش نیست که کتابخونه یا همون فایلای روبی مربوط ب این کتابخونه رو بصورت inner بذاریم توی ریپو
اینطوری هم توی گیت هاب کار نمیکنه؟

چون من مواردی مثل تبدیل اعداد انگلیسی به فارسی رو هم میخوام داشته باشم و اگر بشه بنویسمش!
درحال حاضر از فونت فارسی استفاده کردم.
</div>

**Comment by mehdisadeghi** [comment]
خواهش می‌کنم. اما متاسفانه امکانپذیر نیست. گیتهاب صریحا در مستنداتش ذکر کرده که هیچ فایل یا لایبرری خارجی روبی رو برای وبسایتهای جکیل ساپورت نمی‌کنه مگر تعداد معدودی که پلاگینهای مورد نظر ما رو شامل نمی‌شه.
همین دلیل اصلی استفاده من از سرویس خارجیه. خیلی از این کارها رو می‌تونی البته با جاوااسکریپت هم انجام بدی. فونت شامل محدودیتهایی که گفتم نمی‌شه، فقط کد روبی محدود شده.

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
من این ایشو رو می‌بندم. مشکلی بود دوباره ثبت کنید.
</div>

**Comment by mohsenkhanpour** [comment]
سلام، من هم این مشکل رو دارم. اگر امکان داره یه مقدار توضیح بیشتر بدین درباره اینکه چگونه از سرویس خارجی استفاده کنیم تا بتونیم روی گیت‌هاب درست نمایش بدیم

**Comment by beigirad** [comment]
@mohsenkhanpour 
من با js این رو هندل کردم.
ببین شاید بکارت  اومد.
http://beigirad.ir/blog/add-jalali-date-to-jekyll.html

**Comment by mohsenkhanpour** [comment]
@beigirad ممنون
